---
title: "Itinerary"
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Schedule

- This a rough draft for now please go to the [ideaboard](./googlesheets.html) if you have ideas or want to add more!

## Hanoi

### Thursday, November 9th

- Grab your passports, get on the plane, its time to EMBRACE AN ADVENTURE OF A LIFETIME
- [Flights from SFO to Hanoi](https://www.google.com/travel/flights/search?tfs=CBwQAhojEgoyMDIzLTExLTA5agcIARIDU0ZPcgwIAhIIL20vMGZuZmZAAUgBcAGCAQsI____________AZgBAg&hl=en&gl=us&curr=USD)
- [Flights from HNL to Hanoi](https://www.google.com/travel/flights/search?tfs=CBwQAhojEgoyMDIzLTExLTA5agcIARIDSE5McgwIAhIIL20vMGZuZmZAAUgBcAGCAQsI____________AZgBAg&hl=en&gl=us&curr=USD)

### Friday, November 10th

- Check-in to the airbnb
- Grab a drink somewhere if we feel like it/if things are open

### Saturday, November 11th (borrowed from Day 1 of pre-planning section)

- Morning: Begin your day with a visit to the historical heart of Hanoi, the Hoan Kiem Lake, surrounded by beautiful temples and gardens. Take a leisurely stroll across the iconic red Huc Bridge to Ngoc Son Temple, set on an island in the lake.
- Afternoon: Explore the Old Quarter's bustling streets, filled with vibrant markets and charming shops. Satisfy your cravings with a delightful Vietnamese lunch at Cha Ca Thang Long, renowned for its mouthwatering fish specialty.
   - Perhaps a lunchtime cooking class? 
- Evening & Night: Hanoi Night Market! Only available on the weekends

### Sunday, November 12th 

- Morning: Treat yourself to a lavish breakfast at the Sofitel Legend Metropole Hanoi, an iconic landmark that exudes colonial-era elegance.
- Afternoon: Engage your senses with a leisurely cyclo tour through the French Quarter. Visit the grand Opera House and other architectural marvels.
- Evening: Experience the epitome of luxury at the elegant Le Beaulieu Restaurant, housed within the Sofitel Legend Metropole Hanoi. Savor the delicate flavors of gourmet French cuisine while being serenaded by live music.

### Monday, November 13th

- Day 1 of 2Day1Night cruise 
- Schedule of our cruise [here](https://letheatrecruises.com/2-day-1-night-cruise/)

### Tuesday, November 14th

- Day 2 of 2Day1Night cruise
- Return to Hanoi
- Take off of Bangkok, look at [flights](https://www.google.com/travel/flights/search?tfs=CBwQAhowEgoyMDIzLTExLTE0QA5IF1AAWBdqDAgCEggvbS8wZm5mZnIMCAISCC9tLzBmbjJnQAFIAXABggELCP___________wGYAQI&tfu=EgYIARABGAA&hl=en&gl=us&curr=USD)
- Check into hotel/airbnb

### Wednesday, November 15th

- Bri and the bois bool in bangkok 
- Friendsgiving in Thailand

### Thursday, November 16th 

- Bri and the bois bool in bangkok 

### Friday, November 17th - Sunday, November 19th

- Kevin and Zelos do unspeakable things

